name: stuzonefinal
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  ## -- STATE MANAGEMENT
  get: ^4.6.5
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  provider: ^6.0.5

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^6.1.5
  intl: ^0.18.1


  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.2.16
  image_picker: ^1.0.4
  pedometer: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  decimal: ^2.3.3
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.0
  otp_text_field: ^1.1.3
  pinput: ^3.0.1
  google_maps_flutter_web: ^0.5.4+2
  firebase_storage: ^11.2.8
  local_auth: ^2.1.7
  geolocator: ^10.1.0
  location: ^5.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icon/
    - assets/images/
    - assets/images/lostProperty/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/